baseURL = 'https://www.robertgatti.com/'
languageCode = 'en-us'
title = 'A curious individual'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
#googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Robert - Creator. Technologist. Thinker."

# Appearance settings
theme = 'auto'
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "Hi, I'm Robert!"
homeIntroContent = """I like to build things. This is my space on the Internet
where you can find projects I'm currently working on."""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/robertgatti/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/rgatti"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
